name = "blog-xieshi"
compatibility_date = "2026-02-11"
compatibility_flags = ["nodejs_compat"]
[[d1_databases]]
binding = "DB"
database_name = "blog-db"
database_id = "6070ea68-0b22-4653-9837-06542edccf91"